version: 2

sources:
  - name: raw_data
    database: olist_ecommerce
    schema: public
    tables:
      - name: orders
      - name: order_items
      - name: customers
      - name: order_payments